### ISSUE TITLE
Fotos für Anschluss

### ISSUE THREAD

**Issue by matthiassommer** [frankol/ecodesign-homeassistant#1]
Hallo,

kannst du Fotos hochstellen, die den Anschluss an die BWWP, sowie die Verdrahtung mit Waveshare zeigen?
Optimal als kleines Howto-Tutorial.

Vielen Dank

**Comment by frankol** [comment]
Hi,
klar, kein Thema. Ich mach nachher ein paar Bilder.
Ist keine Raketenwisschenschaft. Mich hat Anfangs nur der PV Modus verwirrt. Nach einem Gespräch mit dem Support stellte sich aber schnell heraus, dass eben eine Brücke geschaltet werden musste um per Modbus den PV-Modus aktivieren zu können

**Comment by frankol** [comment]
Drehkopf rausziehen
Abdeckung entfernen (die beiden Schrauben oben enfernen und nach oben hinausschieben)
![IMG_20240224_104120](https://github.com/frankol/ecodesign-homeassistant/assets/28876168/6155b596-2617-4bb5-b0c7-9f680bc5a699)

Durch etwas Gewalt die Metallabdeckung nach links oder rechts hinausziehen

![IMG_20240224_104217](https://github.com/frankol/ecodesign-homeassistant/assets/28876168/cfa771d8-70e4-4e0e-9b55-d52ff26b562a)


Kabel verbinden

![IMG_20240224_103945](https://github.com/frankol/ecodesign-homeassistant/assets/28876168/98b8e890-e982-4a1b-ab61-ec17f2127119)
![IMG_20240224_104250](https://github.com/frankol/ecodesign-homeassistant/assets/28876168/40fea4da-58d7-47ed-81fd-274a072c5fd9)
![IMG_20240224_104305](https://github.com/frankol/ecodesign-homeassistant/assets/28876168/bf70473d-ea65-457c-bc26-d229169aef6f)
